name: Go

on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test -v ./...
